export const GraphicsCards = [
  {
    id: 116,
    brand: "MSI",
    model: "RTX 3050",
    image: "/DESKTOP/RTX3050.webp",
    gpuManufacturer: "NVIDIA",
    graphicsCoprocessor: "NVIDIA GeForce RTX 3050",
    vram: "8GB GDDR6",
    videoOutput: ["DisplayPort", "HDMI"],
    recommendedUses: ["Gaming"],
    includedComponents: ["Graphics card", "Quick setup guide"],
    compatibleDevices: "PCI Express 4.0 slot",
    maxResolution: "4K Ultra HD",
    price: 13500,
  },
  {
    id: 117,
    brand: "MSI",
    model: "RTX 3060",
    image: "/DESKTOP/RTX3060.webp",
    gpuManufacturer: "NVIDIA",
    graphicsCoprocessor: "NVIDIA GeForce RTX 3060",
    vram: "12GB GDDR6",
    videoOutput: ["DisplayPort", "HDMI"],
    recommendedUses: ["Gaming"],
    includedComponents: ["Graphics card", "Quick setup guide"],
    compatibleDevices: "PCI Express 4.0 slot",
    maxResolution: "4K Ultra HD",
    price: 16500,
  },
];
