export const desktopPCs = [
  {
    id: 98,
    brand: "ASUS",
    image: "/DESKTOP/ASUS1.webp",
    model: "PANTIUM 7RD",
    cpu: "Pentium",
    ram: "8GB DDR4",
    storage: "SSD 128GB + HDD 500GB",
    gpu: null,
    screenSize: null,
    price: 4500,
    extraFeatures: ["كيسة مزودة براك متنقل اصلي", "باور سبلاي قوي", "قابلة للتحديث"],
  },
  {
    id: 99,
    brand: "HP",
    image: "/DESKTOP/600G3.webp",
    model: "600 G3",
    cpu: "Intel Core i5-7th Gen",
    ram: "4GB DDR4",
    storage: "SSD 128GB + HDD 500GB",
    gpu: null,
    screenSize: null,
    price: 6000,
    extraFeatures: ["تصميم أنيق ومناسب للمكاتب"],
  },
  {
    id: 100,
    brand: "FUJITSU",
    image: "/DESKTOP/FUJITSU1.webp",
    model: "PC",
    cpu: "Intel Core i3-8100",
    ram: "8GB DDR4",
    storage: "SSD M.2 128GB + HDD 500GB",
    gpu: "Intel Integrated Graphics",
    screenSize: null,
    price: 4999,
    extraFeatures: ["جيل ثامن مخصص للشركات والمشاريع"],
  },
  {
    id: 101,
    brand: "HP",
    image: "/DESKTOP/800G2.webp",
    model: "800 G2",
    cpu: "Intel Core i5-6th Gen",
    ram: "8GB DDR4",
    storage: "SSD 200GB + HDD 500GB",
    gpu: "Intel Integrated Graphics",
    screenSize: null,
    price: null, 
    extraFeatures: ["أداء قوي مع دعم VGA Intel"],
  },
  {
    id: 102,
    brand: "Custom / Local",
    image: "/DESKTOP/Custom.webp",
    model: "",
    cpu: "Intel Core i5 (جيل سادس)",
    ram: "غير مذكور",
    storage: "غير محدد",
    gpu: null,
    screenSize: null,
    price: 6500,
    extraFeatures: ["تجميعة اقتصادية ضمن فئة 6500 جنيه، تصميم جميل وقابل للتحديث"],
  },
  {
    id: 103,
    brand: "HP",
    image: "/DESKTOP/705G4.webp",
    model: "705 G4 Tiny",
    cpu: "Ryzen 5 2400",
    ram: "8GB DDR4",
    storage: "SSD 256GB",
    gpu: null,
    screenSize: null,
    price: 6500,
    extraFeatures: ["حجم صغير مع أداء ممتاز"],
  },
  {
    id: 104,
    brand: "HP",
    image: "/DESKTOP/Z440.webp",
    model: "Z440",
    cpu: "Xeon E5-1603",
    ram: "8GB",
    storage: "SSD 128GB + HDD 500GB",
    gpu: "1GB",
    screenSize: null,
    price: 7000,
    extraFeatures: ["ورك ستيشن للمهام الشاقة", "مزود بمحول 700W"],
  },
  {
    id: 105,
    brand: "HP",
    image: "/DESKTOP/Z440.webp",
    model: "Z440",
    cpu: "Xeon E5-2670",
    ram: "8GB",
    storage: "SSD 128GB + HDD 500GB",
    gpu: "1GB",
    screenSize: null,
    price: 8000,
    extraFeatures: ["ورك ستيشن للمهام الشاقة", "مزود بمحول 700W"],
  },
  {
    id: 106,
    brand: "HP",
    image: "/DESKTOP/Z440.webp",
    model: "Z440",
    cpu: "Xeon E5-2670",
    ram: "8GB",
    storage: "SSD 128GB + HDD 500GB",
    gpu: "2GB GTX",
    screenSize: null,
    price: 9999,
    extraFeatures: null,
  },
  {
    id: 107,
    brand: "HP",
    image: "/DESKTOP/Z440.webp",
    model: "Z440",
    cpu: "Xeon E5-2680",
    ram: "8GB",
    storage: "SSD 128GB + HDD 500GB",
    gpu: "2GB Quadro K2000",
    screenSize: null,
    price: 9999,
    extraFeatures: null,
  },
  {
    id: 108,
    brand: "HP",
    image: "/DESKTOP/Z440.webp",
    model: "Z440",
    cpu: "Xeon E5-2680",
    ram: "16GB",
    storage: "SSD 128GB + HDD 500GB",
    gpu: "4GB Quadro K2200",
    screenSize: null,
    price: 11000,
    extraFeatures: null,
  },
  {
    id: 109,
    brand: "HP",
    image: "/DESKTOP/Z440.webp",
    model: "Z440",
    cpu: "Xeon E5-2680",
    ram: "16GB",
    storage: "SSD 128GB + HDD 500GB",
    gpu: "6GB GTX 1060",
    screenSize: null,
    price: 13500,
    extraFeatures: null,
  },
  {
    id: 110,
    brand: "HP",
    image: "/DESKTOP/Z440.webp",
    model: "Z440",
    cpu: "Xeon E5-2697",
    ram: "32GB",
    storage: "SSD 2000GB",
    gpu: "RTX 3050",
    screenSize: null,
    price: 26000,
    extraFeatures: null,
  },
  {
    id: 111,
    brand: "HP",
    image: "/DESKTOP/Z840.webp",
    model: "Z840",
    cpu: "Dual Xeon E5-2697",
    ram: "64GB DDR4",
    storage: "SSD 2000GB",
    gpu: "RTX 3050",
    screenSize: null,
    price: 45000,
    extraFeatures: ["ورك ستيشن جبارة جدًا، قابلة لأقصى تحديثات"],
  },
];

export const GamingPCs = [
  {
    id: 112,
    brand: "AMD",
    image: "/DESKTOP/4650G.webp",
    model: "Ryzen 5 4650G",
    cpu: "Ryzen 5 4650G",
    ram: "8GB",
    storage: "SSD 128GB + HDD 500GB",
    vga: "Integrated Radeon Graphics (8)",
    price: 10000,
  },
  {
    id: 113,
    brand: "AMD",
    image: "/DESKTOP/4700S.webp",
    model: "Ryzen 7 4700S",
    cpu: "Ryzen 7 4700S",
    ram: "16GB",
    storage: "SSD 128GB + HDD 500GB",
    vga: "Integrated Radeon Graphics",
    price: 11000,
  },
  {
    id: 114,
    brand: "AMD",
    image: "/DESKTOP/2600.webp",
    model: "Ryzen 5 2600",
    cpu: "Ryzen 5 2600 (6 Cores)",
    ram: "8GB",
    storage: "SSD 128GB + HDD 500GB",
    vga: "NVIDIA GTX 4GB",
    price: 12000,
  },
  {
    id: 115,
    brand: "AMD",
    image: "/DESKTOP/5600G.webp",
    model: "Ryzen 5 5600G",
    cpu: "Ryzen 5 5600G (6 Cores)",
    ram: "8GB",
    storage: "SSD 128GB + HDD 500GB",
    vga: "Integrated Radeon Graphics",
    price: 14000,
  },
];
