const laptopsVersatile = [
  {
    id: 1,
    brand: "DELL",
    image: "/DELL/DELL1.webp",
    model: "D630",
    cpu: "C2DUO INTEL",
    storage: "80GB HDD",
    ram: "2GB",
    gpu: null,
    screenSize: '14"',
    price: 2000,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 2,
    brand: "DELL",
    image: "/DELL/DELL2.webp",
    model: "6500",
    cpu: "i7 INTEL",
    storage: "128GB SSD",
    ram: null,
    gpu: null,
    screenSize: '17"',
    price: 3500,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 3,
    brand: "HP",
    image: "/HP/HP1.webp",
    model: "820",
    cpu: "i5",
    storage: "128GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '12"',
    price: 5000,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 4,
    brand: "ASUS",
    image: "/ASUS/ASUS1.webp",
    model: "E410",
    cpu: "CELERON INTEL",
    storage: "128GB SSD",
    ram: "4GB",
    gpu: null,
    screenSize: '14.1"',
    price: 7500,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 5,
    brand: "HP",
    image: "/HP/HP2.webp",
    model: "820 g3",
    cpu: "i5",
    storage: "256GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '12"',
    price: 6999,
    nickname: "أبو دهشوم",
    extraFeatures: ["شاشة رائعة", "كاميرا أمامية وخلفية", "بوزن الريشة"],
  },
  {
    id: 6,
    brand: "HP",
    image: "/HP/HP3.webp",
    model: "820 g4",
    cpu: "i5",
    storage: "256GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '12"',
    price: 8000,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 7,
    brand: "DELL",
    image: "/DELL/DELL3.webp",
    model: "6520",
    cpu: "i5 INTEL HD",
    storage: "320GB HDD",
    ram: "4GB",
    gpu: "NVIDIA",
    screenSize: '15.6"',
    price: 4500,
    nickname: null,
    extraFeatures: ["لوحة مفاتيح كاملة", "شاشة كبيرة", "اقتصادي"],
  },
  {
    id: 8,
    brand: "DELL",
    image: "/DELL/DELL4.webp",
    model: "XT3",
    cpu: "i5 INTEL",
    storage: "240GB SSD",
    ram: "4GB",
    gpu: null,
    screenSize: '12" TOUCH',
    price: 4000,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 9,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO2.webp",
    model: "T520",
    cpu: "i7 MQ INTEL",
    storage: "500GB HDD",
    ram: "8GB",
    gpu: "NVIDIA 1GB DDR3",
    screenSize: '15.6"',
    price: 4750,
    nickname: "لاب توب دبابة",
    extraFeatures: ["مواصفات عالية", "سعر اقتصادي جدًا"],
  },
  {
    id: 10,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO1.webp",
    model: "T520",
    cpu: "i7 MQ INTEL",
    storage: "128GB SSD",
    ram: "8GB",
    gpu: "NVIDIA 1GB DDR3",
    screenSize: '15.6"',
    price: 4999,
    nickname: "لاب توب دبابة",
    extraFeatures: ["مواصفات عالية", "سعر اقتصادي جدًا"],
  },
  {
    id: 11,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO2.webp",
    model: "T530",
    cpu: "i7 MQ INTEL",
    storage: "128GB SSD",
    ram: "8GB",
    gpu: "NVIDIA 1GB DDR3",
    screenSize: '15.6"',
    price: 5500,
    nickname: "لاب توب دبابة",
    extraFeatures: ["مواصفات عالية", "سعر اقتصادي"],
  },
  {
    id: 12,
    brand: "DELL",
    image: "/DELL/DELL5.webp",
    model: "6520",
    cpu: "i5 INTEL",
    storage: "128GB SSD",
    ram: "8GB",
    gpu: "NVIDIA",
    screenSize: '15.6"',
    price: 5250,
    nickname: null,
    extraFeatures: [
      "شاشة كبيرة",
      "لوحة مفاتيح كاملة",
      "كاميرا أمامية",
      "اقتصادي",
    ],
  },
  {
    id: 13,
    brand: "HP",
    image: "/HP/HP4.webp",
    model: "8560",
    cpu: "i5 INTEL",
    storage: "128GB SSD",
    ram: "8GB",
    gpu: "NVIDIA",
    screenSize: '15.6"',
    price: 5750,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 14,
    brand: "HP",
    image: "/HP/HP5.webp",
    model: "840 g2",
    cpu: "i5",
    storage: "128GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '14"',
    price: 6500,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 15,
    brand: "HP",
    image: "/HP/HP6.webp",
    model: "840 g3",
    cpu: "i5",
    storage: "128GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '14"',
    price: 7500,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 16,
    brand: "HP",
    image: "/HP/HP7.webp",
    model: "1040 g4",
    cpu: "i7",
    storage: "256GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '14"',
    price: 9999,
    nickname: null,
    extraFeatures: null,
  },
  {
    id: 17,
    brand: "HP",
    image: "/HP/HP8.webp",
    model: "840 g5 ELITEBOOK",
    cpu: "i5",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '14" FHD',
    price: 10000,
    nickname: null,
    extraFeatures: ["USB 3", "HDMI", "Webcam", "شبيه أبل", "شياكة رهيبة"],
  },
  {
    id: 18,
    brand: "DELL",
    image: "/DELL/DELL6.webp",
    model: "6800",
    cpu: "i7 4RD",
    storage: "128GB SSD + 500GB HDD",
    ram: "8GB",
    gpu: "NVIDIA 2GB",
    screenSize: '17"',
    price: 8000,
    nickname: null,
    extraFeatures: ["جرافيك", "شاشة عملاقة"],
  },
  {
    id: 19,
    brand: "DELL",
    image: "/DELL/DELL7.webp",
    model: "6540",
    cpu: "i7 4RD",
    storage: "240GB SSD",
    ram: "8GB",
    gpu: "ATI 2GB",
    screenSize: '15.6"',
    price: 8000,
    nickname: null,
    extraFeatures: ["جرافيك", "تصميمات"],
  },
  {
    id: 20,
    brand: "HP",
    image: "/HP/HP9.webp",
    model: "ZBOOK",
    cpu: "i7 4RD",
    storage: "240GB SSD",
    ram: "16GB",
    gpu: "NVIDIA 2GB",
    screenSize: '15.6"',
    price: 9000,
    nickname: null,
    extraFeatures: ["جرافيك"],
  },
  {
    id: 21,
    brand: "HP",
    image: "/HP/HP10.webp",
    model: "ZBOOK",
    cpu: "i7 4RD",
    storage: "128GB SSD + 500GB HDD",
    ram: "16GB",
    gpu: "NVIDIA 4GB",
    screenSize: '17"',
    price: 10000,
    nickname: null,
    extraFeatures: [
      "لابات الجيل السادس والسابع والثامن",
      "كروت خارجية 2GB فما فوق",
      "مخصصة للتصميمات والجرافيك",
      "شواحن أصلية",
      "ضغط عالي",
      "بالضمان",
    ],
  },
  {
    id: 22,
    brand: "HP",
    image: "/HP/HP13.webp",
    model: "PROBOOK G5-EE",
    cpu: "Intel Pentium Silver N5030",
    storage: "128GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '11.1" TOUCH',
    price: 6000,
    nickname: "شقلباظ",
    extraFeatures: [
      "وزن لطيف",
      "شاحن عادي",
      "شاشة تاتش قابلة للطي",
      "كاميرا أمامية وخلفية",
      "حواف كاوتش للصدمات",
      "Type-C",
      "لون أزرق مبهج",
    ],
  },
  {
    id: 23,
    brand: "HP",
    image: "/HP/HP14.webp",
    model: "PROBOOK G5-EE",
    cpu: "Intel Pentium Silver N5030",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '11.1" TOUCH',
    price: 6750,
    nickname: "شقلباظ",
    extraFeatures: [
      "وزن لطيف",
      "شاحن عادي",
      "شاشة تاتش قابلة للطي",
      "كاميرا أمامية وخلفية",
      "حواف كاوتش للصدمات",
      "Type-C",
      "لون أزرق مبهج",
    ],
  },
  {
    id: 24,
    brand: "HP",
    image: "/HP/HP5.webp",
    model: "Elitebook 745 G4",
    cpu: "A10",
    storage: "128GB SSD",
    ram: "8GB DDR4",
    gpu: "ATI 1GB (Up to 4GB)",
    screenSize: '14.1" FHD',
    price: 7750,
    nickname: null,
    extraFeatures: ["Webcam", "LAN", "USB"],
  },
  {
    id: 25,
    brand: "HP",
    image: "/HP/HP2.webp",
    model: "PROBOOK 640 g2",
    cpu: "i5-6rd",
    storage: "240GB SSD M.2",
    ram: "8GB DDR4",
    gpu: null,
    screenSize: '14.1" FHD',
    price: 6500,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "HDMI", "USB3", "Microphone", "Camera"],
  },
  {
    id: 26,
    brand: "HP",
    image: "/HP/HP3.webp",
    model: "PROBOOK 645 G4",
    cpu: "Ryzen 5 2500U",
    storage: "128GB SSD + 500GB HDD",
    ram: "8GB DDR4",
    gpu: "ATI 1GB (Up to 4GB)",
    screenSize: '14.1" FHD',
    price: 8500,
    nickname: "أبو دهشوم",
    extraFeatures: ["Webcam", "LAN", "USB", "WiFi"],
  },
  {
    id: 27,
    brand: "HP",
    image: "/HP/HP4.webp",
    model: "Elitebook 745 G5",
    cpu: "Ryzen 3 2500U",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "ATI 1GB",
    screenSize: '14" FHD',
    price: 8000,
    nickname: null,
    extraFeatures: ["USB3", "HDMI", "Webcam", "شبيه أبل", "شياكة رهيبة"],
  },
  {
    id: 28,
    brand: "HP",
    image: "/HP/HP5.webp",
    model: "Elitebook 745 G6",
    cpu: "Ryzen 3 3300U",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "ATI 1GB",
    screenSize: '14" FHD',
    price: 9000,
    nickname: null,
    extraFeatures: ["USB3", "HDMI", "Webcam", "شبيه أبل", "شياكة رهيبة"],
  },
  {
    id: 29,
    brand: "DELL",
    image: "/DELL/DELL8.webp",
    model: "5490",
    cpu: "i3-8rd",
    storage: "256GB NVMe SSD",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '14.1" FHD',
    price: 8000,
    nickname: "الباز أفندي",
    extraFeatures: ["جيل ثامن", "شيك"],
  },
  {
    id: 30,
    brand: "DELL",
    image: "/DELL/DELL9.webp",
    model: "5490",
    cpu: "i5-8rd",
    storage: "256GB NVMe SSD",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '14.1" FHD',
    price: 9000,
    nickname: "الباز أفندي",
    extraFeatures: ["جيل ثامن", "شيك"],
  },
  {
    id: 31,
    brand: "DELL",
    image: "/DELL/DELL12.webp",
    model: "5285",
    cpu: "i5-8rd",
    storage: "256GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '12.1" TOUCH',
    price: 8000,
    nickname: "شقلباظ",
    extraFeatures: [],
  },
  {
    id: 32,
    brand: "HP",
    image: "/HP/HP6.webp",
    model: "PROBOOK 650 g2",
    cpu: "i5-6rd",
    storage: "256GB SSD",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '15.6" FHD',
    price: 8500,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "HD Webcam", "USB3"],
  },
  {
    id: 33,
    brand: "HP",
    image: "/HP/HP7.webp",
    model: "PROBOOK 650 g3",
    cpu: "i5-7rd",
    storage: "256GB SSD",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '15.6" FHD',
    price: 9000,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "HD Webcam", "USB3"],
  },
  {
    id: 34,
    brand: "HP",
    image: "/HP/HP8.webp",
    model: "Elitebook 850 g3",
    cpu: "i5",
    storage: "256GB SSD",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '15.6" FHD',
    price: 11000,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "HD Webcam", "USB3"],
  },
  {
    id: 35,
    brand: "HP",
    image: "/HP/HP9.webp",
    model: "Elitebook 850 g3",
    cpu: "i5",
    storage: "256GB SSD",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '15.6" FHD Touch',
    price: 12000,
    nickname: null,
    extraFeatures: ["شاشة تاتش", "Backlit Keyboard", "HD Webcam", "USB3"],
  },
  {
    id: 36,
    brand: "HP",
    image: "/HP/HP10.webp",
    model: "Elitebook 850 g4",
    cpu: "i5",
    storage: "256GB SSD",
    ram: "16GB DDR4",
    gpu: "Intel",
    screenSize: '15.6" FHD',
    price: 12000,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "HD Webcam", "USB3"],
  },
  {
    id: 37,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO3.webp",
    model: "e595",
    cpu: "Ryzen 3500U",
    storage: "240GB SSD",
    ram: "8GB DDR4",
    gpu: "2GB",
    screenSize: '15.6" FHD IPS',
    price: 11999,
    nickname: null,
    extraFeatures: ["خيال علمي", "شاشة ليس لها مثيل", "Backlit Keyboard"],
  },
  {
    id: 38,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO4.webp",
    model: "e595",
    cpu: "Ryzen 3500U",
    storage: "240GB SSD",
    ram: "16GB DDR4",
    gpu: "2GB",
    screenSize: '15.6" FHD IPS',
    price: 12500,
    nickname: null,
    extraFeatures: ["خيال علمي", "شاشة ليس لها مثيل", "Backlit Keyboard"],
  },
  {
    id: 39,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO5.webp",
    model: "e595",
    cpu: "Ryzen 3500U",
    storage: "240GB SSD + 320GB HDD",
    ram: "16GB DDR4",
    gpu: "2GB",
    screenSize: '15.6" FHD IPS',
    price: 13000,
    nickname: null,
    extraFeatures: ["خيال علمي", "شاشة ليس لها مثيل", "Backlit Keyboard"],
  },
  {
    id: 40,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO6.webp",
    model: "e595",
    cpu: "Ryzen 3500U",
    storage: "240GB SSD + 1TB HDD",
    ram: "16GB DDR4",
    gpu: "2GB",
    screenSize: '15.6" FHD IPS',
    price: 14000,
    nickname: null,
    extraFeatures: ["خيال علمي", "شاشة ليس لها مثيل", "Backlit Keyboard"],
  },
  {
    id: 41,
    brand: "HP",
    image: "/HP/HP11.webp",
    model: "Elitebook 850 g5",
    cpu: "i5",
    storage: "256GB SSD",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '15.6" FHD',
    price: 13500,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "HD Webcam", "USB3"],
  },
  {
    id: 42,
    brand: "HP",
    image: "/HP/HP1.webp",
    model: "Elitebook 850 g5",
    cpu: "i5",
    storage: "500GB SSD",
    ram: "16GB DDR4",
    gpu: "Intel",
    screenSize: '15.6" FHD',
    price: 14500,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "HD Webcam", "USB3"],
  },
  {
    id: 43,
    brand: "HP",
    image: "/HP/HP2.webp",
    model: "Elitebook 735 G5",
    cpu: "Ryzen 5 2500U",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "ATI 1GB",
    screenSize: '13" FHD',
    price: 9999,
    nickname: null,
    extraFeatures: ["USB3", "HDMI", "Webcam", "شبيه أبل", "مقاس متوسط"],
  },
  {
    id: 44,
    brand: "HP",
    image: "/HP/HP3.webp",
    model: "Elitebook 830 G5",
    cpu: "i5 U",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '13" FHD',
    price: 10000,
    nickname: null,
    extraFeatures: ["USB3", "HDMI", "Webcam", "شياكة"],
  },
  {
    id: 45,
    brand: "HP",
    image: "/HP/HP4.webp",
    model: "Elitebook 830 G5",
    cpu: "i5 U",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '13" FHD Touch',
    price: 11000,
    nickname: null,
    extraFeatures: ["شاشة تاتش", "USB3", "HDMI", "Webcam", "شياكة"],
  },
  {
    id: 46,
    brand: "HP",
    image: "/HP/HP5.webp",
    model: "Elitebook 745 G5",
    cpu: "Ryzen 5 2500U",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "ATI 1GB",
    screenSize: '14" FHD',
    price: 10000,
    nickname: null,
    extraFeatures: ["USB3", "HDMI", "Webcam", "شبيه أبل", "مقاس متوسط"],
  },
  {
    id: 47,
    brand: "HP",
    image: "/HP/HP6.webp",
    model: "Elitebook 745 G6",
    cpu: "Ryzen 5 3500U",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "ATI 2GB",
    screenSize: '14.1" FHD',
    price: 11000,
    nickname: null,
    extraFeatures: ["USB3", "HDMI", "Webcam", "شبيه أبل", "مقاس متوسط"],
  },
  {
    id: 48,
    brand: "HP",
    image: "/HP/HP7.webp",
    model: "Elitebook 745 G6",
    cpu: "Ryzen 5 3500U",
    storage: "512GB SSD M.2",
    ram: "16GB DDR4",
    gpu: "ATI 2GB",
    screenSize: '14.1" FHD',
    price: 12000,
    nickname: null,
    extraFeatures: ["USB3", "HDMI", "Webcam", "شبيه أبل", "مقاس متوسط"],
  },
  {
    id: 49,
    brand: "HP",
    image: "/HP/HP12.webp",
    model: "PROBOOK G5-EE",
    cpu: "P-SILVER N5030 INTEL",
    storage: "128GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '11.1" TOUCH',
    price: 6500,
    nickname: "مستر بلو الشقلباظ العجيب",
    extraFeatures: [
      "لون أزرق مبهج",
      "وزن لطيف جدًا",
      "شحن Type-C وعادي",
      "شاشة تاتش قابلة للقلب والتحويل لتابلت",
      "كاميرا أمامية وخلفية FHD",
      "حواف كاوتش للصدمات",
      "تعريب لوحة مفاتيح أصلي",
      "حالة بلاده",
    ],
  },
  {
    id: 50,
    brand: "HP",
    image: "/HP/HP13.webp",
    model: "PROBOOK G5-EE",
    cpu: "P-SILVER N5030 INTEL",
    storage: "256GB SSD M.2",
    ram: "8GB DDR4",
    gpu: "Intel",
    screenSize: '11.1" TOUCH',
    price: 7500,
    nickname: "مستر بلو الشقلباظ العجيب",
    extraFeatures: [
      "لون أزرق مبهج",
      "وزن لطيف جدًا",
      "شحن Type-C وعادي",
      "شاشة تاتش قابلة للقلب والتحويل لتابلت",
      "كاميرا أمامية وخلفية FHD",
      "حواف كاوتش للصدمات",
      "حالة بلاده",
    ],
  },
  {
    id: 51,
    brand: "DELL",
    image: "/DELL/DELL11.webp",
    model: "7390",
    cpu: "i5 8RD",
    storage: "256GB SSD",
    ram: "8GB DDR4",
    gpu: null,
    screenSize: '13.3" FHD 360X',
    price: 15500,
    nickname: null,
    extraFeatures: [
      "شاشة قابلة للدوران 360 درجة",
      "يتحول لتابلت",
      "مايكروفون",
      "كاميرا رائعة",
      "تحفة فنية من Dell",
    ],
  },
  {
    id: 52,
    brand: "HP",
    image: "/HP/HP14.webp",
    model: "1030",
    cpu: "i5 7RD",
    storage: "256GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '13.3" FHD',
    price: 12000,
    nickname: null,
    extraFeatures: [
      "شقلباظ",
      "شاشة قابلة للدوران 360 درجة",
      "يدعم الرسم بالقلم",
      "شياكة بلا حدود",
      "وزن الريشة",
    ],
  },
  {
    id: 53,
    brand: "HP",
    image: "/HP/HP12.webp",
    model: "830 x360",
    cpu: "i5 8RD",
    storage: "256GB SSD NVMe",
    ram: "16GB DDR4",
    gpu: null,
    screenSize: '13" FHD TOUCH',
    price: 14000,
    nickname: null,
    extraFeatures: [
      "شقلباظ",
      "جيل ثامن",
      "إمكانية التحويل لتابلت",
      "يدعم اللمس باليد أو بالقلم",
      "شاشة تدور 360 درجة",
    ],
  },
  {
    id: 54,
    brand: "HP",
    image: "/HP/HP1.webp",
    model: "1030",
    cpu: "i5 8RD",
    storage: "256GB SSD",
    ram: "8GB",
    gpu: null,
    screenSize: '13.3" FHD',
    price: 16000,
    nickname: "خيال علمي",
    extraFeatures: [],
  },
];

// Graphics Laptops
const laptopsGraphics = [
  {
    id: 55,
    brand: "DELL",
    image: "/DELL/DELL5.webp",
    model: "PRECISION 3520",
    cpu: "Core i5-7440HQ",
    storage: "SSD 256GB",
    ram: "8GB",
    gpu: "NVIDIA Quadro M620 2GB",
    screenSize: '15.6" FHD Touch',
    price: 13750,
    nickname: "لاب حلو وبوزن خفيف",
    extraFeatures: [
      "Touch Screen",
      "Backlit Keyboard",
      "WiFi",
      "LAN",
      "USB 3.0",
      "HDMI",
      "Card Reader",
      "Type-C",
    ],
  },
  {
    id: 56,
    brand: "HP",
    image: "/HP/HP2.webp",
    model: "ZBOOK G3",
    cpu: "Core i7-6820H",
    storage: "SSD 256GB + HDD 320GB",
    ram: "8GB",
    gpu: "Intel",
    screenSize: '15.6" FHD',
    price: 12000,
    nickname: "حسابات وبرمجة",
    extraFeatures: [
      "USB 3.0",
      "Backlit Keyboard",
      "WiFi",
      "Bluetooth",
      "LAN",
      "Webcam",
    ],
  },
  {
    id: 57,
    brand: "HP",
    image: "/HP/HP3.webp",
    model: "ZBOOK G3",
    cpu: "Core i7-6820H",
    storage: "SSD 256GB",
    ram: "16GB",
    gpu: "NVIDIA M1000 2GB",
    screenSize: '15.6" FHD',
    price: 14750,
    nickname: "لاب قليل الأدب جدا",
    extraFeatures: [
      "USB 3.0",
      "Backlit Keyboard",
      "WiFi",
      "Bluetooth",
      "LAN",
      "Webcam",
    ],
  },
  {
    id: 58,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO1.webp",
    model: "P50",
    cpu: "Core i7-6700HQ",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "NVIDIA M1000M 4GB",
    screenSize: '15.6" FHD',
    price: 15000,
    nickname: "شاشة تراكب رائعة",
    extraFeatures: [
      "WiFi",
      "Webcam",
      "LAN",
      "USB 3.0",
      "HDMI",
      "Card Reader",
      "Type-C",
    ],
  },
  {
    id: 59,
    brand: "HP",
    image: "/HP/HP4.webp",
    model: "ZBOOK G3",
    cpu: "Core i7-6820H",
    storage: "SSD 256GB + HDD 500GB",
    ram: "16GB",
    gpu: "NVIDIA M1000 2GB",
    screenSize: '15.6" FHD',
    price: 15000,
    nickname: "برمجة جرافيك تصميمات",
    extraFeatures: [
      "USB 3.0",
      "Backlit Keyboard",
      "WiFi",
      "Bluetooth",
      "LAN",
      "Webcam",
    ],
  },
  {
    id: 60,
    brand: "DELL",
    image: "/DELL/DELL1.webp",
    model: "3530",
    cpu: "Core i5-8400H",
    storage: "SSD 500GB",
    ram: "16GB",
    gpu: "NVIDIA 4GB",
    screenSize: '15.6" FHD',
    price: 16000,
    nickname: "هندسة وجرافيك",
    extraFeatures: ["Backlit Keyboard"],
  },
  {
    id: 61,
    brand: "DELL",
    image: "/DELL/DELL2.webp",
    model: "7710",
    cpu: "Core i7-HQ",
    storage: "SSD 256GB + HDD",
    ram: "16GB",
    gpu: "NVIDIA/ATI 2GB",
    screenSize: '17.1" FHD',
    price: 13000,
    nickname: "دبابة جرافيك وبرمجة",
    extraFeatures: ["Backlit Keyboard", "USB 3.0", "HD Webcam"],
  },
  {
    id: 62,
    brand: "DELL",
    image: "/DELL/DELL3.webp",
    model: "7720",
    cpu: "Core i7-HQ",
    storage: "SSD 256GB",
    ram: "16GB",
    gpu: "NVIDIA/ATI 4GB",
    screenSize: '17.1" FHD',
    price: 16000,
    nickname: "دبابة جرافيك وبرمجة",
    extraFeatures: ["Backlit Keyboard", "USB 3.0", "HD Webcam"],
  },
  {
    id: 63,
    brand: "DELL",
    image: "/DELL/DELL4.webp",
    model: "7720",
    cpu: "Core i7-HQ",
    storage: "SSD 256GB + HDD 500GB",
    ram: "16GB",
    gpu: "NVIDIA P3000 6GB",
    screenSize: '17.1" FHD',
    price: 17000,
    nickname: "دبابة جرافيك وبرمجة",
    extraFeatures: ["Backlit Keyboard", "USB 3.0", "HD Webcam"],
  },
  {
    id: 64,
    brand: "DELL",
    image: "/DELL/DELL5.webp",
    model: "7720 Xeon",
    cpu: "Xeon 6RD",
    storage: "SSD 256GB + HDD 500GB",
    ram: "16GB",
    gpu: "NVIDIA P5000 16GB",
    screenSize: '17.1" FHD',
    price: 20000,
    nickname: "",
    extraFeatures: ["Backlit Keyboard", "HD Webcam"],
  },
];

// Graphics Gen 8 Laptops
const laptopsGraphicsGen8 = [
  {
    id: 65,
    brand: "FUJITSU",
    image: "/FUJITSU/FUJITSU1.webp",
    model: "Celsius 780",
    cpu: "Core i7-8850H",
    storage: "SSD 256GB NVMe",
    ram: "8GB DDR4",
    gpu: "NVIDIA P1000 4GB",
    screenSize: '15.6" FHD',
    price: 18000,
    nickname: "كسر زيرو - تيتانيوم للشغل الشاق",
    extraFeatures: [
      "Backlit Keyboard",
      "Made in Japan",
      "Warranty",
      "Free Spare Parts",
    ],
  },
  {
    id: 66,
    brand: "FUJITSU",
    image: "/FUJITSU/FUJITSU2.webp",
    model: "Celsius 780",
    cpu: "Core i7-8850H",
    storage: "SSD 512GB NVMe",
    ram: "16GB DDR4",
    gpu: "NVIDIA P1000 4GB",
    screenSize: '15.6" FHD',
    price: 19000,
    nickname: "كسر زيرو - تيتانيوم للشغل الشاق",
    extraFeatures: [
      "Backlit Keyboard",
      "Made in Japan",
      "Warranty",
      "Free Spare Parts",
    ],
  },
  {
    id: 67,
    brand: "FUJITSU",
    image: "/FUJITSU/FUJITSU3.webp",
    model: "Celsius 780",
    cpu: "Core i7-8850H",
    storage: "SSD 512GB NVMe",
    ram: "16GB DDR4",
    gpu: "NVIDIA P2000 4GB",
    screenSize: '15.6" FHD Touch',
    price: 20000,
    nickname: "كسر زيرو - تيتانيوم للشغل الشاق - شاشة تاتش جبارة",
    extraFeatures: [
      "Touch Screen",
      "Backlit Keyboard",
      "Made in Japan",
      "Warranty",
      "Free Spare Parts",
    ],
  },
  {
    id: 68,
    brand: "HP",
    image: "/HP/HP5.webp",
    model: "ZBOOK G5",
    cpu: "Core i7-8850H",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "NVIDIA Quadro 4GB",
    screenSize: '15.6" FHD',
    price: 21000,
    nickname: null,
    extraFeatures: [],
  },
  {
    id: 69,
    brand: "HP",
    image: "/HP/HP6.webp",
    model: "ZBOOK G6",
    cpu: "Core i5-9400H",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "NVIDIA T1000 4GB",
    screenSize: '17" FHD',
    price: 21000,
    nickname: "المتوّحش بصوت الرعد",
    extraFeatures: [
      "Backlit Keyboard",
      "WiFi",
      "Bluetooth",
      "LAN",
      "Webcam",
      "USB 3.0",
    ],
  },
  {
    id: 70,
    brand: "HP",
    image: "/HP/HP7.webp",
    model: "ZBOOK G6",
    cpu: "Core i7-9850H",
    storage: "SSD 512GB",
    ram: "32GB",
    gpu: "NVIDIA 4GB",
    screenSize: '15.6" FHD',
    price: 24000,
    nickname: "هندسة يا هندسة",
    extraFeatures: [
      "Backlit Keyboard",
      "WiFi",
      "Bluetooth",
      "LAN",
      "Webcam",
      "USB 3.0",
    ],
  },
];

// Graphics High End Laptops
const laptopsGraphicsHighEnd = [
  {
    id: 71,
    brand: "HP",
    image: "/HP/HP8.webp",
    model: "ZBOOK G7 FURY",
    cpu: "Core i7-10850H",
    storage: "SSD 512GB",
    ram: "32GB",
    gpu: "NVIDIA T2000 4GB",
    screenSize: '15.6" FHD',
    price: 27000,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "WiFi", "USB 3.0"],
  },
  {
    id: 72,
    brand: "HP",
    image: "/HP/HP9.webp",
    model: "ZBOOK G7 FURY",
    cpu: "Core i7-10850H",
    storage: "SSD 512GB",
    ram: "32GB",
    gpu: "RTX 3000 6GB",
    screenSize: '15.6" FHD',
    price: 32000,
    nickname: null,
    extraFeatures: ["Backlit Keyboard", "WiFi", "USB 3.0"],
  },
  {
    id: 73,
    brand: "HP",
    image: "/HP/HP10.webp",
    model: "ZBOOK FURY G8",
    cpu: "Core i7-11800",
    storage: "SSD 512GB",
    ram: "32GB",
    gpu: "RTX A2000",
    screenSize: null,
    price: 35000,
    nickname: null,
    extraFeatures: [],
  },
  {
    id: 74,
    brand: "HP",
    image: "/HP/HP11.webp",
    model: "ZBOOK FURY G8",
    cpu: "Core i7-11800",
    storage: "SSD 1TB",
    ram: "32GB",
    gpu: "RTX A2000",
    screenSize: null,
    price: 37000,
    nickname: null,
    extraFeatures: [],
  },
  {
    id: 75,
    brand: "HP",
    image: "/HP/HP1.webp",
    model: "ZBOOK FURY G8",
    cpu: "Core i7-11800",
    storage: "SSD 1TB",
    ram: "64GB",
    gpu: "RTX A2000",
    screenSize: null,
    price: 40000,
    nickname: null,
    extraFeatures: [],
  },
  {
    id: 76,
    brand: "DELL",
    image: "/DELL/DELL6.webp",
    model: "Precision 7530",
    cpu: "Core i5-8400H",
    storage: "SSD NVMe 500GB",
    ram: "16GB",
    gpu: "NVIDIA P2000 4GB",
    screenSize: '15.6" FHD',
    price: 19000,
    nickname: "هندسة وجرافيك تقيل",
    extraFeatures: ["Backlit Keyboard"],
  },
  {
    id: 77,
    brand: "DELL",
    image: "/DELL/DELL7.webp",
    model: "Precision 7730",
    cpu: "Core i5-8400H",
    storage: "SSD NVMe 500GB",
    ram: "16GB",
    gpu: "NVIDIA P3200 6GB",
    screenSize: '17" FHD',
    price: 22000,
    nickname: "عرض ميتسابش",
    extraFeatures: ["Backlit Keyboard"],
  },
  {
    id: 78,
    brand: "DELL",
    image: "/DELL/DELL8.webp",
    model: "Precision 7540",
    cpu: "Core i5-9400H",
    storage: "SSD NVMe 500GB",
    ram: "16GB",
    gpu: "NVIDIA T2000 4GB",
    screenSize: '15.6" FHD',
    price: 21000,
    nickname: "هندسة وجرافيك تقيل",
    extraFeatures: ["Backlit Keyboard"],
  },
  {
    id: 79,
    brand: "DELL",
    image: "/DELL/DELL9.webp",
    model: "Precision 7740",
    cpu: "Core i5-9400H",
    storage: "SSD NVMe 500GB",
    ram: "16GB",
    gpu: "RTX 3000 6GB",
    screenSize: '17" FHD',
    price: 23000,
    nickname: "",
    extraFeatures: ["Backlit Keyboard"],
  },
  {
    id: 80,
    brand: "HP",
    image: "/HP/HP2.webp",
    model: "ZBOOK G5",
    cpu: "Core i7-8665U",
    storage: "SSD 512GB",
    ram: "16GB DDR4",
    gpu: "ATI WX 3200 4GB DDR5",
    screenSize: '15.6" FHD',
    price: 19000,
    nickname: "أحدث موديلات زي بوك - شياكة قوي",
    extraFeatures: [],
  },
  {
    id: 81,
    brand: "DELL",
    image: "/DELL/DELL10.webp",
    model: "Precision 7530",
    cpu: "Core i7-8850H",
    storage: "SSD NVMe 512GB",
    ram: "16GB DDR4",
    gpu: "NVIDIA Quadro P2000 4GB",
    screenSize: '15.6" FHD',
    price: 22000,
    nickname: "جرافيك وهندسة",
    extraFeatures: ["وحش الجيل الثامن"],
  },
  {
    id: 82,
    brand: "DELL",
    image: "/DELL/DELL11.webp",
    model: "Precision 7730",
    cpu: "Core i7-8850H",
    storage: "SSD NVMe 512GB",
    ram: "16GB",
    gpu: "NVIDIA Quadro P3200 6GB",
    screenSize: '17" FHD IPS 1080',
    price: 23000,
    nickname: "لهيطة أبو اللاهليط",
    extraFeatures: [],
  },
  {
    id: 83,
    brand: "DELL",
    image: "/DELL/DELL8.webp",
    model: "Precision 7730",
    cpu: "Core i7-8850H",
    storage: "SSD 512GB",
    ram: "32GB",
    gpu: "NVIDIA Quadro P4200 8GB",
    screenSize: '17" FHD IPS',
    price: 30000,
    nickname: "جهاز 17 بوصة جبار بكارت شاشة قوى",
    extraFeatures: ["Backlit Keyboard"],
  },
];

// New Laptops with warranty
const laptopsNewWithWarranty = [
  {
    id: 84,
    brand: "ASUS",
    image: "/ASUS/ASUS2.webp",
    model: "X509F",
    cpu: "Intel Core i3",
    storage: "SSD 256GB",
    ram: "8GB",
    screenSize: '15.6"',
    price: 14000,
    warranty: "1 year",
    extraFeatures: [],
  },
  {
    id: 85,
    brand: "HP",
    image: "/HP/HP3.webp",
    model: "G8",
    cpu: "Athlon Gold",
    storage: "SSD 256GB + HDD 1TB",
    ram: "8GB",
    screenSize: '15.6"',
    price: 15000,
    warranty: "1 year",
    extraFeatures: ["تصميم أنيق"],
  },
  {
    id: 86,
    brand: "HP",
    image: "/HP/HP4.webp",
    model: "3515",
    cpu: "Ryzen 3 3250U",
    storage: "SSD NVMe 128GB + HDD 320GB",
    ram: "8GB",
    gpu: "ATI 2GB",
    screenSize: '15.6"',
    price: 15000,
    warranty: "1 year",
    extraFeatures: ["Backlit Keyboard", "وزن الريشة", "شيك جداً"],
  },
  {
    id: 87,
    brand: "HP",
    image: "/HP/HP5.webp",
    model: "3515",
    cpu: "Ryzen 3",
    storage: "SSD 500GB",
    ram: "16GB",
    screenSize: '15.6"',
    price: 17000,
    warranty: "1 year",
    extraFeatures: ["Backlit Keyboard"],
  },
  {
    id: 88,
    brand: "ACER",
    image: "/ACER/ACER1.webp",
    model: "A515",
    cpu: "Intel Core i5-12450H",
    storage: "SSD 500GB",
    ram: "8GB",
    screenSize: '15.6"',
    price: 23000,
    warranty: "1 year",
    extraFeatures: [],
  },
  {
    id: 89,
    brand: "HP",
    image: "/HP/HP6.webp",
    model: "3510",
    cpu: "Intel Core i3 11th Gen",
    storage: "HDD 1TB + SSD 256GB",
    ram: "8GB",
    screenSize: '15.6"',
    price: 15000,
    warranty: "1 year",
    extraFeatures: ["شيك"],
  },
  {
    id: 90,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO3.webp",
    model: "FLEX TOUCH",
    cpu: null,
    storage: "128GB",
    ram: "4GB",
    screenSize: '11.1" FHD Touch',
    price: 10000,
    warranty: "1 year",
    extraFeatures: [],
  },
  {
    id: 91,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO4.webp",
    model: "LOQ",
    cpu: "Intel Core i5-12450H",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "RTX 3050",
    screenRefreshRate: "144Hz",
    price: 40000,
    warranty: "1 year",
    extraFeatures: ["v6"],
  },
  {
    id: 92,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO5.webp",
    model: "LOQ",
    cpu: "Intel Core i7-13650HX",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "RTX 4050",
    screenRefreshRate: "144Hz",
    price: 49000,
    warranty: "1 year",
    extraFeatures: ["v6"],
  },
  {
    id: 93,
    brand: "LENOVO",
    image: "/LENOVO/LENOVO6.webp",
    model: "LOQ",
    cpu: "Ryzen 7 7435HS",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "RTX 4060",
    price: 49000,
    warranty: "1 year",
    extraFeatures: [],
  },
  {
    id: 94,
    brand: "HP",
    image: "/HP/HP7.webp",
    model: "Victus",
    cpu: "Intel Core i5-12450H",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "RTX 3050",
    screenRefreshRate: "144Hz",
    price: 33000,
    warranty: "1 year",
    extraFeatures: [],
  },
  {
    id: 95,
    brand: "HP",
    image: "/HP/HP8.webp",
    model: "Victus",
    cpu: "Intel Core i5-12450H",
    storage: "SSD 512GB",
    ram: "32GB",
    gpu: "RTX 3050",
    screenRefreshRate: "144Hz",
    price: 34000,
    warranty: "1 year",
    extraFeatures: [],
  },
  {
    id: 96,
    brand: "HP",
    image: "/HP/HP9.webp",
    model: "Victus",
    cpu: "Ryzen 5 8645",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "RTX 4050 6GB",
    price: 41000,
    warranty: "1 year",
    extraFeatures: [],
  },
  {
    id: 97,
    brand: "HP",
    image: "/HP/HP10.webp",
    model: "Victus",
    cpu: "Intel Core i5-13420H",
    storage: "SSD 512GB",
    ram: "16GB",
    gpu: "RTX 3050 6GB",
    screenSize: '15.6"',
    screenRefreshRate: "144Hz",
    price: 40000,
    warranty: "1 year",
    extraFeatures: ["Backlit Keyboard"],
  },
];

export {
  laptopsGraphics,
  laptopsGraphicsGen8,
  laptopsGraphicsHighEnd,
  laptopsNewWithWarranty,
  laptopsVersatile,
};

export const laptopsAll = [...laptopsGraphics, ...laptopsGraphicsGen8, ...laptopsGraphicsHighEnd, ...laptopsNewWithWarranty, ...laptopsVersatile];